version: '2'

services:
  #MySQL設定
  db:
    image: mysql:5.7.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - default
  #phpMyAdmin設定
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 7414:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - default
  #前端設定
  frontend:
    build: 
      context: ./yBooking-Frontend/
      dockerfile: Dockerfile
    #restart: always
    ports:
      - 80:80
    networks:
      - default
  #後端設定
  backend:
    build: 
      context: ./yBooking-Backend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    command: gunicorn app:app -b 0.0.0.0:5000
    networks:
      - default
volumes:
  db_data:
networks:
  default:
    driver: bridge

